apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      volumes:
        - name: vol-config
          hostPath:
            path: /Users/ruan/workspace/go/scaffold/apiserver/configs
            type: Directory
      containers:
        - name: apiserver
          image: wukongsun/apiserver-amd64:2cd18d6
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: vol-config
              mountPath: /etc/apiserver
          ports:
            - containerPort: 8080
              name: insecure
              protocol: TCP
            - containerPort: 8081
              name: rpc
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
spec:
  selector:
    app: apiserver
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    targetPort: 8080
    port: 8080
    nodePort: 30080
  - name: rpc
    protocol: TCP
    targetPort: 8081
    port: 8081
    nodePort: 30081


